version: "3"
services:
  pytorch-for-gfx803-dev:
    image: woodrex/pytorch-for-gfx803-dev:latest
    container_name: pytorch-for-gfx803-dev
    network_mode: host
    user: root
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    environment:
      - args="--use-pytorch-cross-attention"
    # keep container open
    command: ["tail", "-f", "/dev/null"]

